/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/reminders": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Reminders
     * @description List scheduled reminders ordered by start time.
     *
     *     Returns:
     *         All scheduled reminders.
     */
    get: operations["list_reminders_reminders_get"]
    put?: never
    /**
     * Create Reminder
     * @description Create a scheduled reminder.
     *
     *     Args:
     *         payload: Reminder data supplied by the client.
     *
     *     Returns:
     *         The stored reminder.
     */
    post: operations["create_reminder_reminders_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/reminders/conflicts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Check Reminder Conflicts
     * @description Check whether a proposed reminder overlaps scheduled reminders.
     *
     *     Args:
     *         payload: Proposed reminder time window.
     *
     *     Returns:
     *         Conflict check result.
     */
    post: operations["check_reminder_conflicts_reminders_conflicts_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/reminders/{reminder_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Reminder
     * @description Cancel a scheduled reminder.
     *
     *     Args:
     *         reminder_id: Reminder identifier.
     *
     *     Returns:
     *         Empty response when the reminder was cancelled.
     *
     *     Raises:
     *         HTTPException: If the reminder does not exist or is not scheduled.
     */
    delete: operations["delete_reminder_reminders__reminder_id__delete"]
    options?: never
    head?: never
    /**
     * Update Reminder
     * @description Update a scheduled reminder.
     *
     *     Args:
     *         reminder_id: Reminder identifier.
     *         payload: Partial reminder update supplied by the client.
     *
     *     Returns:
     *         The updated reminder.
     *
     *     Raises:
     *         HTTPException: If the reminder does not exist or is not scheduled.
     */
    patch: operations["update_reminder_reminders__reminder_id__patch"]
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Health
     * @description Return a lightweight health response.
     *
     *     Returns:
     *         The service status.
     */
    get: operations["read_health_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * ReminderConflictCheck
     * @description Reminder conflict check payload.
     */
    ReminderConflictCheck: {
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string
      /** Duration Minutes */
      duration_minutes?: number | null
      /** Exclude Reminder Id */
      exclude_reminder_id?: string | null
    }
    /**
     * ReminderConflictRead
     * @description Reminder conflict check response model.
     */
    ReminderConflictRead: {
      /** Has Conflicts */
      has_conflicts: boolean
      /** Conflicts */
      conflicts: components["schemas"]["ReminderRead"][]
      /**
       * Skipped Conflict Check
       * @default false
       */
      skipped_conflict_check: boolean
      /** Reason */
      reason?: string | null
    }
    /**
     * ReminderCreate
     * @description Reminder creation payload.
     */
    ReminderCreate: {
      /** Title */
      title: string
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string
      /** Duration Minutes */
      duration_minutes?: number | null
      /** Details */
      details?: string | null
      /**
       * Time Kind
       * @default exact
       * @enum {string}
       */
      time_kind: "exact" | "date_only"
      /** Source Call Id */
      source_call_id?: string | null
    }
    /**
     * ReminderRead
     * @description Reminder API response model.
     */
    ReminderRead: {
      /** Id */
      id: string
      /** Title */
      title: string
      /** Details */
      details: string | null
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string
      /** Duration Minutes */
      duration_minutes: number | null
      /**
       * Time Kind
       * @enum {string}
       */
      time_kind: "exact" | "date_only"
      /** Status */
      status: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /** Source Call Id */
      source_call_id: string | null
    }
    /**
     * ReminderUpdate
     * @description Reminder update payload.
     */
    ReminderUpdate: {
      /** Title */
      title?: string | null
      /** Starts At */
      starts_at?: string | null
      /** Duration Minutes */
      duration_minutes?: number | null
      /** Details */
      details?: string | null
      /** Time Kind */
      time_kind?: ("exact" | "date_only") | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_reminders_reminders_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReminderRead"][]
        }
      }
    }
  }
  create_reminder_reminders_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReminderCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReminderRead"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  check_reminder_conflicts_reminders_conflicts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReminderConflictCheck"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReminderConflictRead"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_reminder_reminders__reminder_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        reminder_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_reminder_reminders__reminder_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        reminder_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReminderUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReminderRead"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  read_health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: string
          }
        }
      }
    }
  }
}
